# Meta Data for SEO

## Homepage
title = "Pico-Go"
titleSeparator = "-"
titleAddition = "Autocompletion and a REPL console for the Raspberry Pi Pico."
description = "Autocompletion and a REPL console for the Raspberry Pi Pico."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "cpwooduk"
twitterCreator = "cpwooduk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/cpwooduk"
schemaGitHub = "https://github.com/cpwood/Pico-Go"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Pico-Go? <a class=\"alert-link\" href=\"https://github.com/cpwood/Pico-Go/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/cpwood/Pico-Go-Web"
editPage = false
